enum Status {
  STATUS_ACTIVE = 'ACTIVE',
  STATUS_INACTIVE = 'INACTIVE',
  STATUS_DELETED = 'DELETED',
  STATUS_PENDING = 'PENDING',
  STATUS_BLOCKED = 'BLOCKED',
  STATUS_RESOLVED = 'RESOLVED',
}

enum JobStatus {
  ACTIVE = 'ACTIVE',
  FINISHED = 'FINISHED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}

enum UserStatus {
  STATUS_ACTIVE = 'ACTIVE',
  STATUS_INACTIVE = 'INACTIVE',
  STATUS_DELETED = 'DELETED',
  STATUS_PENDING = 'PENDING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  PENDING_KYC = 'PENDING_KYC',
  APPROVED = 'APPROVED',
}

enum UserRole {
  USER_ROLE_ADMIN = 'ADMIN',
  USER_ROLE_CUSTOMER = 'CUSTOMER',
  USER_ROLE_ARTIST = 'ARTIST',
}

enum NotificationStatus {
  SEEN = "SEEN",
  UNSEEN = "UNSEEN"
}

enum NotificationType {
  JOB_REQUEST = "JOB_REQUEST",
  ALERT = "ALERT"
}

export { UserRole, Status, UserStatus, JobStatus, NotificationStatus, NotificationType };
